version: "3"


services:


  influxdb:
    image: influxdb:3.5-core
    container_name: influxdb
    command:
      - sh
      - -c
      - |
        influxdb3 serve --node-id=node0 --object-store=file --data-dir=/var/lib/influxdb3/data  --admin-token-file /etc/influxdb3/token.json
    volumes:
      - ./influx/data:/var/lib/influxdb3 # Configuration directory
      - ./influx/config:/etc/influxdb3
    ports:
      - "8181:8181"
    restart: unless-stopped

  influxdb3-explorer:
    image: influxdata/influxdb3-ui
    container_name: influxdb3-explorer
    ports:
      - 8888:80
    restart: unless-stopped
    command: ["--mode=admin"]
    depends_on:
      - influxdb


  telegraf:
    image: telegraf:1.36.3-alpine
    container_name: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf:/etc/telegraf/
    restart: unless-stopped  



  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:4.8.3
    container_name: syslog-ng
    environment:
      - TZ=Europe/Rome
    links:
      - telegraf  
    volumes:
      - ./syslog/syslog-ng.conf:/config/syslog-ng.conf
      - ./syslog/log:/var/log #optional
    ports:
      - 514:5514/udp
    restart: unless-stopped 



    
  grafana:
    container_name: grafana
    image: grafana/grafana:12.3.0-18765596677
    user: "1001:1001"
    volumes:
      - ./grafana:/var/lib/grafana
    links:
      - influxdb   
    ports:
      - 3000:3000
    restart: unless-stopped  